"""animals table

Revision ID: 016df00ac148
Revises: cd69482098ae
Create Date: 2023-03-15 15:56:15.004752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016df00ac148'
down_revision = 'cd69482098ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('have_house', sa.Boolean(), nullable=True))
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('have_house')

    # ### end Alembic commands ###
