"""users table

Revision ID: 3488c0e8be94
Revises: ce873c9417f5
Create Date: 2023-02-23 23:11:21.910432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3488c0e8be94'
down_revision = 'ce873c9417f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('aa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aa', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
