"""table

Revision ID: 401763793d87
Revises: 016df00ac148
Create Date: 2023-03-30 21:18:54.189112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401763793d87'
down_revision = '016df00ac148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partners')
    # ### end Alembic commands ###
