"""documents table

Revision ID: 460c4169d9a5
Revises: 8e7fd34654d6
Create Date: 2023-03-03 18:14:37.823947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460c4169d9a5'
down_revision = '8e7fd34654d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
