"""config table

Revision ID: 513562c0e9aa
Revises: 460c4169d9a5
Create Date: 2023-03-07 20:08:17.215716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513562c0e9aa'
down_revision = '460c4169d9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    # ### end Alembic commands ###
