"""users table

Revision ID: 812c26ee6f2d
Revises: b32bb9040d88
Create Date: 2023-02-23 23:11:46.387253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812c26ee6f2d'
down_revision = 'b32bb9040d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
