"""empty message

Revision ID: 85167ff2cbbc
Revises: edd5a6116cc7
Create Date: 2023-05-20 17:13:01.291452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85167ff2cbbc'
down_revision = 'edd5a6116cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
