"""animals table

Revision ID: cd69482098ae
Revises: a0909748a218
Create Date: 2023-03-12 23:34:46.308566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd69482098ae'
down_revision = 'a0909748a218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
