"""empty message

Revision ID: ce36321b9793
Revises: 812dd50a5a01
Create Date: 2023-04-12 16:03:23.359606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce36321b9793'
down_revision = '812dd50a5a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smi_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smi_timestamp'))

    op.drop_table('smi')
    # ### end Alembic commands ###
